from dataclasses import dataclass

from app.graph.schema import (
    EntityType,
    RelationshipType,
    RELATIONSHIP_GUIDANCE,
)


ONTOLOGY_VERSION = "2.0"


@dataclass(
    frozen=True
)
class OntologyProfile:
    """
    Defines the semantic vocabulary allowed
    for one class of documents.

    Every domain profile contains the
    universal core plus its domain-specific
    extension.

    Profiles may also be composed from
    multiple domain extensions.
    """

    name: str

    version: str

    entity_types: frozenset[
        EntityType
    ]

    relationship_types: frozenset[
        RelationshipType
    ]

    @property
    def entity_type_values(
        self,
    ) -> set[str]:
        return {
            entity_type.value
            for entity_type
            in self.entity_types
        }

    @property
    def relationship_type_values(
        self,
    ) -> set[str]:
        return {
            relationship_type.value
            for relationship_type
            in self.relationship_types
        }

    @property
    def extractable_relationship_types(
        self,
    ) -> frozenset[
        RelationshipType
    ]:
        """
        Relationships generated by the semantic
        graph extractor.

        Structural relationships such as
        CONTAINS and MENTIONS are generated by
        TraceGraph itself and therefore must not
        be requested from the LLM.
        """

        return frozenset(
            relationship_type

            for relationship_type
            in self.relationship_types

            if relationship_type
            not in {
                RelationshipType.CONTAINS,
                RelationshipType.MENTIONS,
            }
        )

    @property
    def extractable_relationship_values(
        self,
    ) -> set[str]:
        return {
            relationship_type.value

            for relationship_type
            in self.extractable_relationship_types
        }

    def get_relationship_guidance(
        self,
    ) -> dict[str, str]:
        """
        Return semantic guidance only for
        relationships enabled by this ontology.
        """

        return {
            relationship_type.value:
                RELATIONSHIP_GUIDANCE[
                    relationship_type.value
                ]

            for relationship_type
            in self.extractable_relationship_types

            if (
                relationship_type.value
                in RELATIONSHIP_GUIDANCE
            )
        }


# =========================================================
# UNIVERSAL CORE
# =========================================================


CORE_ENTITY_TYPES = frozenset(
    {
        EntityType.PERSON,
        EntityType.ORGANIZATION,
        EntityType.TEAM,
        EntityType.PROJECT,
        EntityType.PRODUCT,
        EntityType.CONCEPT,
        EntityType.LOCATION,
        EntityType.EVENT,
    }
)


CORE_RELATIONSHIP_TYPES = frozenset(
    {
        # -----------------------------------------
        # Structural relationships.
        #
        # These are created by TraceGraph rather
        # than extracted by the LLM.
        # -----------------------------------------

        RelationshipType.CONTAINS,
        RelationshipType.MENTIONS,

        # -----------------------------------------
        # Universal semantic relationships.
        # -----------------------------------------

        RelationshipType.USES,
        RelationshipType.WORKS_ON,
        RelationshipType.OWNED_BY,
        RelationshipType.PART_OF,
        RelationshipType.DEPENDS_ON,
        RelationshipType.DEVELOPED_BY,
        RelationshipType.RELATED_TO,
        RelationshipType.LOCATED_IN,
        RelationshipType.GENERATED_BY,
        RelationshipType.APPLIES_TO,
    }
)


# =========================================================
# RESEARCH / TECHNICAL EXTENSION
# =========================================================


RESEARCH_ENTITY_TYPES = frozenset(
    {
        EntityType.TECHNOLOGY,
        EntityType.MODEL,
        EntityType.METHOD,
        EntityType.DATASET,
        EntityType.METRIC,
    }
)


RESEARCH_RELATIONSHIP_TYPES = frozenset(
    {
        RelationshipType.TRAINED_ON,
        RelationshipType.EVALUATED_ON,
        RelationshipType.EXPLAINED_BY,
    }
)


# =========================================================
# CAREER / RESUME EXTENSION
# =========================================================


CAREER_ENTITY_TYPES = frozenset(
    {
        EntityType.ROLE,
        EntityType.SKILL,
        EntityType.DEGREE,
        EntityType.CERTIFICATION,
        EntityType.EXPERIENCE,
        EntityType.TECHNOLOGY,
    }
)


CAREER_RELATIONSHIP_TYPES = frozenset(
    {
        RelationshipType.WORKED_AT,
        RelationshipType.HAS_ROLE,
        RelationshipType.HAS_SKILL,
        RelationshipType.EARNED_DEGREE,
        RelationshipType.CERTIFIED_IN,
    }
)


# =========================================================
# POLICY / COMPLIANCE EXTENSION
# =========================================================


POLICY_ENTITY_TYPES = frozenset(
    {
        EntityType.POLICY,
        EntityType.REQUIREMENT,
        EntityType.REGULATION,
        EntityType.CONTROL,
        EntityType.EXCEPTION,
        EntityType.PROCEDURE,
    }
)


POLICY_RELATIONSHIP_TYPES = frozenset(
    {
        RelationshipType.REQUIRES,
        RelationshipType.PROHIBITS,
        RelationshipType.GOVERNED_BY,
        RelationshipType.HAS_EXCEPTION,
    }
)


# =========================================================
# CONTRACT / LEGAL EXTENSION
# =========================================================


CONTRACT_ENTITY_TYPES = frozenset(
    {
        EntityType.PARTY,
        EntityType.CLAUSE,
        EntityType.OBLIGATION,
        EntityType.RIGHT,
        EntityType.REQUIREMENT,
    }
)


CONTRACT_RELATIONSHIP_TYPES = frozenset(
    {
        RelationshipType.HAS_OBLIGATION,
        RelationshipType.GRANTS_RIGHT,
        RelationshipType.APPLIES_TO_PARTY,
        RelationshipType.TERMINATES_ON,
        RelationshipType.REQUIRES,
    }
)


# =========================================================
# STANDARD ONTOLOGY PROFILES
# =========================================================


GENERAL_ONTOLOGY = OntologyProfile(
    name="general",
    version=ONTOLOGY_VERSION,

    entity_types=(
        CORE_ENTITY_TYPES
    ),

    relationship_types=(
        CORE_RELATIONSHIP_TYPES
    ),
)


RESEARCH_ONTOLOGY = OntologyProfile(
    name="research",
    version=ONTOLOGY_VERSION,

    entity_types=(
        CORE_ENTITY_TYPES
        | RESEARCH_ENTITY_TYPES
    ),

    relationship_types=(
        CORE_RELATIONSHIP_TYPES
        | RESEARCH_RELATIONSHIP_TYPES
    ),
)


CAREER_ONTOLOGY = OntologyProfile(
    name="career",
    version=ONTOLOGY_VERSION,

    entity_types=(
        CORE_ENTITY_TYPES
        | CAREER_ENTITY_TYPES
    ),

    relationship_types=(
        CORE_RELATIONSHIP_TYPES
        | CAREER_RELATIONSHIP_TYPES
    ),
)


POLICY_ONTOLOGY = OntologyProfile(
    name="policy",
    version=ONTOLOGY_VERSION,

    entity_types=(
        CORE_ENTITY_TYPES
        | POLICY_ENTITY_TYPES
    ),

    relationship_types=(
        CORE_RELATIONSHIP_TYPES
        | POLICY_RELATIONSHIP_TYPES
    ),
)


CONTRACT_ONTOLOGY = OntologyProfile(
    name="contract",
    version=ONTOLOGY_VERSION,

    entity_types=(
        CORE_ENTITY_TYPES
        | CONTRACT_ENTITY_TYPES
    ),

    relationship_types=(
        CORE_RELATIONSHIP_TYPES
        | CONTRACT_RELATIONSHIP_TYPES
    ),
)


# =========================================================
# PROFILE REGISTRY
# =========================================================


ONTOLOGY_PROFILES: dict[
    str,
    OntologyProfile,
] = {
    profile.name: profile

    for profile in (
        GENERAL_ONTOLOGY,
        RESEARCH_ONTOLOGY,
        CAREER_ONTOLOGY,
        POLICY_ONTOLOGY,
        CONTRACT_ONTOLOGY,
    )
}


# =========================================================
# COMPOSITION ORDER
# =========================================================


PROFILE_COMPOSITION_ORDER = (
    "research",
    "career",
    "policy",
    "contract",
)


# =========================================================
# ONTOLOGY PROFILE COMPOSITION
# =========================================================


def compose_ontology_profiles(
    names: (
        list[str]
        | tuple[str, ...]
        | set[str]
    ),
) -> OntologyProfile:
    """
    Compose one or more TraceGraph ontology
    profiles into one active ontology.

    Every specialized ontology already contains
    the universal core, therefore composition
    performs a union of:

    - entity types
    - relationship types

    Examples:

        ["policy", "contract"]
            ->
        policy+contract

        ["research", "career"]
            ->
        research+career

        []
            ->
        general

    Composition is canonical and
    order-independent.

    Therefore:

        ["policy", "contract"]

    and:

        ["contract", "policy"]

    both produce:

        policy+contract

    Stable naming is important because ontology
    profile names participate in:

    - graph extraction cache identity
    - Neo4j provenance
    - document metadata
    - API responses
    """

    normalized_names: set[str] = set()

    # -------------------------------------------------
    # Normalize and validate requested profiles.
    # -------------------------------------------------

    for name in names:
        normalized = (
            name.strip()
            .casefold()
        )

        if not normalized:
            continue

        if (
            normalized
            not in ONTOLOGY_PROFILES
        ):
            valid_profiles = (
                ", ".join(
                    sorted(
                        ONTOLOGY_PROFILES
                    )
                )
            )

            raise ValueError(
                "Unknown ontology profile "
                f"'{name}'. "
                "Valid profiles: "
                f"{valid_profiles}"
            )

        # -----------------------------------------
        # GENERAL contributes only the universal
        # core.
        #
        # Every specialized profile already
        # contains that core, so GENERAL does not
        # need to appear in a composed name.
        # -----------------------------------------

        if normalized == "general":
            continue

        normalized_names.add(
            normalized
        )

    # -------------------------------------------------
    # No specialized profiles:
    #
    # Universal-core-only ontology.
    # -------------------------------------------------

    if not normalized_names:
        return GENERAL_ONTOLOGY

    # -------------------------------------------------
    # Canonical ordering.
    #
    # This prevents:
    #
    # contract+policy
    #
    # and:
    #
    # policy+contract
    #
    # from becoming different ontology identities.
    # -------------------------------------------------

    ordered_names = [
        profile_name

        for profile_name
        in PROFILE_COMPOSITION_ORDER

        if (
            profile_name
            in normalized_names
        )
    ]

    # -------------------------------------------------
    # One specialized ontology:
    #
    # Return the registered singleton rather than
    # creating an equivalent duplicate profile.
    # -------------------------------------------------

    if len(ordered_names) == 1:
        return (
            ONTOLOGY_PROFILES[
                ordered_names[0]
            ]
        )

    # -------------------------------------------------
    # Union entity vocabularies.
    # -------------------------------------------------

    entity_types = frozenset(
        entity_type

        for profile_name
        in ordered_names

        for entity_type
        in (
            ONTOLOGY_PROFILES[
                profile_name
            ]
            .entity_types
        )
    )

    # -------------------------------------------------
    # Union relationship vocabularies.
    #
    # Structural relationships CONTAINS and
    # MENTIONS remain included because each
    # underlying profile contains the core.
    # -------------------------------------------------

    relationship_types = frozenset(
        relationship_type

        for profile_name
        in ordered_names

        for relationship_type
        in (
            ONTOLOGY_PROFILES[
                profile_name
            ]
            .relationship_types
        )
    )

    composed_name = (
        "+".join(
            ordered_names
        )
    )

    return OntologyProfile(
        name=(
            composed_name
        ),

        version=(
            ONTOLOGY_VERSION
        ),

        entity_types=(
            entity_types
        ),

        relationship_types=(
            relationship_types
        ),
    )


# =========================================================
# PROFILE LOOKUP
# =========================================================


def get_ontology_profile(
    name: str,
) -> OntologyProfile:
    """
    Retrieve a TraceGraph ontology profile.

    Supports both registered profiles:

        get_ontology_profile(
            "research"
        )

    and composed profiles:

        get_ontology_profile(
            "policy+contract"
        )
    """

    normalized_name = (
        name.strip()
        .casefold()
    )

    if not normalized_name:
        raise ValueError(
            "Ontology profile name "
            "cannot be empty"
        )

    # -------------------------------------------------
    # Standard registered ontology.
    # -------------------------------------------------

    profile = (
        ONTOLOGY_PROFILES.get(
            normalized_name
        )
    )

    if profile is not None:
        return profile

    # -------------------------------------------------
    # Composed ontology.
    #
    # Example:
    #
    # policy+contract
    #
    # becomes:
    #
    # ["policy", "contract"]
    #
    # and is reconstructed deterministically.
    # -------------------------------------------------

    if "+" in normalized_name:
        component_names = [
            component.strip()

            for component
            in normalized_name.split("+")

            if component.strip()
        ]

        if not component_names:
            raise ValueError(
                "Invalid composed ontology "
                f"profile '{name}'"
            )

        return (
            compose_ontology_profiles(
                component_names
            )
        )

    # -------------------------------------------------
    # Unknown profile.
    # -------------------------------------------------

    valid_profiles = ", ".join(
        sorted(
            ONTOLOGY_PROFILES
        )
    )

    raise ValueError(
        "Unknown ontology profile "
        f"'{name}'. "
        "Valid profiles: "
        f"{valid_profiles}, "
        "or a '+' composition such as "
        "'policy+contract'"
    )